### ISSUE TITLE
As donor, I want to register so that I can use the service.

### ISSUE THREAD

**Issue by ponathanjun** [gcivil-nyu-org/urban-thrifter#11]
**User story**

Registering includes actions such as creating a unique username, password, and verifying their email. While registering, a donor will have to provide a drop off location which can be edited later on.

**Acceptance criteria**
- [x] There is a button near the sign-in panel that leads me to the registration page
- [x] When the user chooses to register as a donor, the donor's registration form will show up
- [x] Following fields are required in the help donor's registration form. The form will prompt an error message if the entry does not meet with the input requirement
  - [x] [Text] Unique username
  - [x] [Text] Email, which will be verified through a link later
  - [ ] [Address Picker] Drop off location
  - [x] [Text] Strong password with security policy (8+ characters, contain any of user name, contain characters from uppercase, lowercase, numbers, special characters)
  - [x] [Text] Password re-enter
- [x] Once registered, in the Donor User Profile database, a new entry will be documented with the following attributes:
  - [x] [string] Username
  - [x] [string] Email
  - [x] [string] Password 
  - [x] [string] Drop off location
  - [x] [int] Donation count (set as 0)
  - [x] [int] Complaint count (set as 0)
- [x] Upon registration, the user will be redirected to a page asking for email verification
- [x] Once verified successfully, the user will be redirected to donor's landing page

**Definition of Done**
1. Acceptance criteria met
2. Code reviewed/ tested
3. Code pushed to the development branch

**Comment by leelightman** [comment]
https://django-map-widgets.readthedocs.io/en/latest/widgets/index.html
