### ISSUE TITLE
As help seeker or donor, I want to log in and logout so that I can get access to the website and its services.

### ISSUE THREAD

**Issue by jgingh7** [gcivil-nyu-org/urban-thrifter#14]
**User story**
A user with an account first inputs the username (email) and password to log in and use features in the app. 

**Acceptance criteria**
- [x] A login section is accessible through the login button. The user could log in with the below credentials
   - [x] username
   - [x] password
- [x] A total of 5 attempts are given to log in. If the credentials do not match, a warning sign will be prompt
- [x] If the login fails 5 times, the user is unable to login for 10 minutes.
- [x] The user is provided with a "forgot password" button to request a password reset sent to his/her email.
- [x] After clicking on forgot password, the user must enter his/her registered email Id to which a password reset link will be sent.
- [x] The email sent contains the reset link along with the registered user's username too.
- [x] On clicking the link the user is redirected to the reset password form.
- [x] After login in the user is able to see the main page (or the pages he/she was recently in) with login profile at the top right.
- [x] After login, the user can logout

**Definition of Done**
1. Acceptance criteria met
2. Code reviewed/ tested
3. Code pushed to the development branch
4. Deployed to Heroku

**Comment by leelightman** [comment]
https://medium.com/@adriennedomingus/locking-users-out-after-invalid-login-attempts-django-a-cache-75cf5988f56c
https://pypi.org/project/django-axes/1.5.0/
https://pypi.org/project/django-lockout/
