### ISSUE TITLE
Forget password for helpseeker user not working

### ISSUE THREAD

**Issue by ronakf11** [gcivil-nyu-org/urban-thrifter#145]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

After registering as a help seeker, I tried resetting password but it doesn't work.

## Expected Behavior

When I try to reset password and I enter my email for so, I should receive password reset link which should redirect me password reset form where I can enter new password twice with a validation to check both are same or not and it should be updated on submit and redirected to login page.

## Current Behavior

When I go for forget password and enter my email, it sends me an email with wrong link with domain as {example.com}.
And even if i try to use the main Heroku instance link instead of example.com with the same query, it redirects to a 404 page.

## Ideas for Improvement

I should receive password reset link which should redirect me password reset form where I can enter new password twice with a validation to check both are same or not and it should be updated on submit and redirected to login page.

## Steps to Reproduce

Example link i get for reset password : http://example.com/password-reset-confirm/MTk/adulia-76f7eddb3c267518336de3fb2c4c7c78/

1.  Go to registration as helpskeeker form.

2. Register successfully

3. try resetting password

4.  the email should have a link with example.com domain which isn't useful

## Context (Environment)

I was trying to reset my password

Just update the email link in mail with the working reset password URL specific to each user.

**Comment by rahulgarg97** [comment]
Hi @ronakf11 , Thanks for pointing that out. Actually, it was because of a minor setting in the admin panel. We just corrected it. Try it out now.

**Comment by rahulgarg97** [comment]
Closing since, it's resolved.
