### ISSUE TITLE
Envelope button for cards on watchlist not working

### ISSUE THREAD

**Issue by i-rahman** [gcivil-nyu-org/urban-thrifter#148]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
Clicking the envelope button on the watch-list notification would take an action like let me message the person who posted the donation

## Current Behavior
Clicking the envelope button on the watch-list notification did not have any effect. It was non responsive and after I refreshed the page the card for the item disappeared 

## Ideas for Improvement
Make the Envelope Icon responsive. 

## Steps to Reproduce
1. Logged in as user
2. Had a Notification alert in watchlist
3. Card with Olaf appeared
4. Clicked on the Envelope Icon
5. Icon was non responsive

## Context (Environment)

I was trying to message the user who posted Olaf, but the messaging was not working.

**Comment by rahulgarg97** [comment]
Hi @i-rahman , could you please elaborate about the issue? Is this issue with the donor account or the help seeker account? If helpseeker, there are are 2 icons (one bell, one envelope). The bell icon is watchlist notification and the envelope icon is basically after the donor accepts/rejects the help seeker's request for an item, the helpseeker gets notified using the envelope icon.

We would like to know more details about the issue in order to resolve this.

**Comment by i-rahman** [comment]
@rahulgarg97 It is the card in the watchlist. It envelope is non responsive. see below:

![step1](https://user-images.githubusercontent.com/30580940/100153335-f87c2600-2e71-11eb-9c7f-156e7da806ba.png)

Hope this helps :)

**Comment by rahulgarg97** [comment]
Ohh, I think the icon was confusing. It's just read/unread notification thing. It's not for messaging.

**Comment by i-rahman** [comment]
In that case, shouldn't it have changed to "open envelope" as I am in the the watchlist. 

Or changed to "open envelope" on clicking it as I have seen it?

I was hoping for some action to have happened.

**Comment by rahulgarg97** [comment]
@leelightman would you like to explain?

**Comment by i-rahman** [comment]
As a user I would assume, if I click on the envelope for a specific notification card in watchlist, it will be marked as read(open envelope). 

I assumed it since nothing about the behaviour of the icon was mentioned in the testing guide for watchlist.

**Comment by leelightman** [comment]
So the watchlist icon is automatically updated. Once you visit the page, it automatically assumes you've read the message. And if you visit again, the icon will change
