### ISSUE TITLE
Cannot edit or cancel donation

### ISSUE THREAD

**Issue by rossy312** [gcivil-nyu-org/urban-thrifter#150]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

After I sign up for a donation (as a donor), nothing happens when I go to my donation and click on the "Edit" or "Cancel" buttons.

## Expected Behavior
I expected to be able to edit or cancel my donation once I submitted it. 

## Current Behavior
Nothing happens when I click the "Edit" or "Cancel" buttons.

## Ideas for Improvement
Make sure these buttons are functional.

## Steps to Reproduce

1. I filled out a form signing up for a donation (3 pumpkin pies).

2. I then clicked on the left-hand "Donations" button, and then the "Available" button, which let me view my donation.

3. I then clicked on the "Edit" and "Cancel" buttons for this donation, and nothing happened.

## Context (Environment)
This is important if the donor wants to make a change to the donation or needs to cancel for whatever reason.

**Comment by rahulgarg97** [comment]
Hi @rossy312, this functionality has not been implemented yet. I think we forgot to mention it in the user guide. Sorry, for the confusion!
