### ISSUE TITLE
Buggy Message Icon

### ISSUE THREAD

**Issue by i-rahman** [gcivil-nyu-org/urban-thrifter#151]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior
Message Icon display unread message soon as we load the profile page

## Current Behavior
Message Icon appears as all read first and then resets to unread

## Steps to Reproduce

1. Log in as a Helpseeker
2. Reserve a Donation Item
3. Logout 
4. Log back in as the Donor
5. Navigate to the profile
6. The message Icon appears as read and then loads again as unread with the number of unread messages

## Context (Environment)

I was just confused whether I have a message or not. Tested in Firefox and Chrome

**Comment by leelightman** [comment]
Sorry for the confusion. Normally it takes a second for ajax to load the number. We could theoretically increase the call per minute, but there is a limitation on Heroku how many requests per minute can be allowed.

**Comment by i-rahman** [comment]
@leelightman Thank you for your reply, but Just as an FYI Heroku doesn't have a limit on Ajax Call. Maybe, be it is something else.
