### ISSUE TITLE
Landing Page UI for resources

### ISSUE THREAD

**Issue by shrutiagarwal28** [gcivil-nyu-org/urban-thrifter#152]
On clicking on the resources tab on the Home page, the web page scrolls down to the resources section. Here you see that there are cards for each kind of item that can either be sought for or donated. On hovering above these cards the card enlarges. This kind of behavior, from a UI perspective, is displayed by a clickable button.

## Expected Behavior

With the card enlarging, it makes you expect a button function from it that would perform some action. 

## Current Behavior

The cards for the item only have the enlarge animation as a highlighting thing.

## Ideas for Improvement

I get that the UI designer wanted to probably highlight each card on hovering it, but they could probably reconsider the animation or design change for that. Or rather make it a clickable link that would redirect the not logged in user to a page where they can see donation successes for that item, and number of donations available.

## Steps to Reproduce

1.  If the team decides to incorporate the suggested enhancement, then they could add an anchor tag for the whole card which links you to a page or a pop-up with more details on the item.

2. 

3. 

4.

**Comment by jgingh7** [comment]
Thanks for your suggestion!
