### ISSUE TITLE
Validation check error when help seeker tries to reserve

### ISSUE THREAD

**Issue by ronakf11** [gcivil-nyu-org/urban-thrifter#153]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When I try to reserve any donation and if I review the form and click reserve without checking the drop-off time tab, it redirects to server 500 error.

## Expected Behavior

It should validate the form and inform the user that the user missed to check the drop-off time tab statically instead of redirecting to another page and showing server 500 error.

## Current Behavior

Currently it just redirects to a page with server 500 error and no information to user of what went wrong.

## Ideas for Improvement

Have a HTML5 required for that field so that user can be informed if in case user missed to select drop-off time.

## Steps to Reproduce

Go to helpskeeker account.
Go to reservations tab and see available reservations.
Select any donation and click on reserve.
Review the donation and click on reserve without checking the drop-off time.
It will redirect to another page with server 500 error and no information to user about what went wrong.

1. Go to helpskeeker account.

2. Go to reservations tab and see available reservations.

3. Select any donation and click on reserve and review the donation and click on reserve without checking the drop-off time.

4. It will redirect to another page with server 500 error and no information to user about what went wrong.

## Context (Environment)

As a user, i wanted to know what i did wrong instead of a server error which i am not aware off.

Just add a HTML5  required attribute to the form element so that user is not able to submit the form without selecting all necessary information.
OR
Have a validation function which displays errors statically

**Comment by deusalexmachina** [comment]
Adding on to Ronak's comment, there is a minor spelling typo on the Donor's side. After confirming a reservation, the confirmation message should say "successfully" instead of "succesfully".
