### ISSUE TITLE
As an HS, getting a 500 error page, if I reserve without choosing the pickup time

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/urban-thrifter#155]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

As a Help Seeker, if I try to reserve an item without choosing the pickup time, it gives me 500 Error Page. 

## Expected Behavior

Either I should be given an error/warning to choose a time. 
OR
Some default time should be selected, especially when there is only a single option.

## Current Behavior

I am taken to "OOPS! Server Error (500)" page

## Ideas for Improvement

You may make the "Drop-off Time" field required

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/55005259/100163145-b1466300-2e7a-11eb-92f1-4064a88ce340.png)

1) Login as HS.
2) Reserve any item without choosing the pick-up time. 

## Context (Environment)

I was trying to reserve a donation but could not reserve it.

**Comment by leelightman** [comment]
Thank you for your time in raising the issue! This bug is duplicated with another bug therefore we will close this and address it with another card. :)
