### ISSUE TITLE
For an HS, the donation count doesn't match

### ISSUE THREAD

**Issue by gauravag2207** [gcivil-nyu-org/urban-thrifter#157]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

For a Help Seeker, the number of donations doesn't match on the Reservations page and on the map. I could see 2 in map and 3 on the reservations page for the 'Food' category.

## Expected Behavior

The number of donations should be the same in both places. (Resource map and Reservations page)

## Current Behavior

The number of donations are different in both places. (Resource map and Reservations page)

## Ideas for Improvement

This is probably because 2 donations are for the same address.

## Steps to Reproduce

![image](https://user-images.githubusercontent.com/55005259/100163027-6cbac780-2e7a-11eb-9fa5-726b3009c038.png)
![image](https://user-images.githubusercontent.com/55005259/100163064-7e03d400-2e7a-11eb-9e55-44026768c91f.png)

1. Login as hs_test1.

2. Check the number of food donations in the resource map. You would see 2.

3. Check the number of donations on the reservations page. You would see 3. 

4.

**Comment by leelightman** [comment]
Thanks for pointing it out for us :) This is due to the overlapping markers which we mentioned in the testing guide.
