### ISSUE TITLE
Add hint for icons

### ISSUE THREAD

**Issue by Huanjin-Zhang** [gcivil-nyu-org/urban-thrifter#165]
## Expected Behavior
When users' cursor hovers over some icons, it is better to show some hints so that users can easily know what the icons are used for.

## Current Behavior
For example, there are some existing resources before users sign in. After users log in, the envelope icon does not respond when users try to click it. It might make users confused.

## Ideas for Improvement
You can try bootstrap popover + Ajax 

## Steps to Reproduce
1. 
2. 
3. 
4.

**Comment by jgingh7** [comment]
Thanks for your time debugging our site! Closing since it is a duplicate
