### ISSUE TITLE
Not getting Activation email link after donor registration

### ISSUE THREAD

**Issue by vinayaknatarajan** [gcivil-nyu-org/urban-thrifter#166]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

I am not getting an account activation email after registering as a donor. I have used my nyu email.

## Expected Behavior

As a donor, I should be  are able to register my account by clicking on the activation link

## Current Behavior

Have not received the activation link.

## Ideas for Improvement

I think this has to do with how the SMTP server is configured for your host "
nyu.django.unchained@gmail.com"

## Steps to Reproduce

1. Go to the signup page and register as a donor.

## Context (Environment)

I am unable to register with my nyu email

**Comment by jgingh7** [comment]
@vinayaknatarajan 
Which email did you use to register?
The NYU email seems to send the verification email VERY slowly.

**Comment by shrutiagarwal28** [comment]
Yes, I faced this issue too

**Comment by jgingh7** [comment]
Thanks your time on debugging our site! Closing since it is a duplicate
