### ISSUE TITLE
Password reset option accepting emails that are not yet registered

### ISSUE THREAD

**Issue by vinayaknatarajan** [gcivil-nyu-org/urban-thrifter#167]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

I am able to request a reset password with an email not yet registered

## Expected Behavior

I should not be able to request reset the password with an unregistered email

## Current Behavior

Password reset option accepting emails that are not yet registered

## Steps to Reproduce

1. Go to the sign-in page and click on reset password.
![Screenshot (10).png](https://images.zenhubusercontent.com/5f6e483d084e4853eaed80b4/f4e94d8b-3c42-43cf-a624-1595d2960458)

2. Enter a random email not yet registered. We get the following prompt after clicking request password reset.
![Screenshot (11)](https://user-images.githubusercontent.com/45198069/100231624-4dad4b80-2ef5-11eb-9c81-41082e944b7b.png)

**Comment by sesha14** [comment]
If the email address provided does not exist in the system, you won’t be receiving an email, but the user won’t receive any error message either. This is a standard practice that prevents the information from leaking to potential attackers. Django inbuilt password reset functionality uses this (our application uses this too). You could go through "Class PasswordResetView" of Django documentation for more information.

**Comment by sesha14** [comment]
If the email address provided does not exist in the system, you won’t be receiving an email, but the user won’t receive any error message either. This is a standard practice that prevents the information from leaking to potential attackers. Django inbuilt password reset functionality uses this (our application uses this too). You could go through "Class PasswordResetView" of Django documentation for more information.
