### ISSUE TITLE
Not getting activation email when I used nyu email

### ISSUE THREAD

**Issue by Chuanqi927** [gcivil-nyu-org/urban-thrifter#171]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Not getting activation email when I used nyu email for registering as helpseeker.

## Expected Behavior

I should receive an activation email to be able to log in.

## Current Behavior
At the first time I registered using my nyu email and did not receive activation email. When I tried to register again, it says username already exists. After I changed the username to other things, it says email already used but I can not log in.

## Ideas for Improvement

No idea why this happens. Gmail worked.

## Steps to Reproduce

1. Go to Homepage

2. Click on join us

3. Click on helpseeker

4. Enter nyu email as email credential

## Context (Environment)

It actually accepted my email and username which I can not reuse. Since I did not recieved activation, I can not log in. These credentails are stored and I have no access for that.

**Comment by leelightman** [comment]
Hi! thanks for the suggestion :D Seems like the activation link does come with delays for NYU email. Feel free to let us know if you still haven't received your activation link!
