### ISSUE TITLE
Some UI buttons are not clickable 

### ISSUE THREAD

**Issue by joshganguly** [gcivil-nyu-org/urban-thrifter#172]
For example,

Logging in as Help Seeker - Open Envelope button in Messages section `https://urban-thrifter.herokuapp.com/reservation/messages/` is not clickable 

Logging in as Donor - 'Edit' or 'Cancel' button in Donations section - `https://urban-thrifter.herokuapp.com/donation/` is not clickable 

## Expected Behavior
On clicking the open envelope button in Messages section one should be able to message who made the donation 
On clicking the Edit/Cancel button in Donations section one should be able to Edit/Cancel the donation 

## Current Behavior
On clicking the open envelope button in Messages section does not do anything
On clicking the  Edit/Cancel button in Donations section does not do anything

## Ideas for Improvement
Add the necessary action to the button

## Steps to Reproduce
1. Go to `https://urban-thrifter.herokuapp.com/reservation/messages/` logged in as HS and click the open envelope button
2. Go to `https://urban-thrifter.herokuapp.com/donation/` logged in as Donor and click the open envelope button

## Context (Environment)
HS User will not be able to message the person who made the donation
Donor User will not be able to edit/cancel the donation

**Comment by leelightman** [comment]
Thanks for the suggestion :)
for the first "unclickable" link -> you are already on the page :) so that's why it seems to be "not clickable"
for the second link - we have mentioned in our testing guide that this has not been implemented yet. Sorry I know it's confusing!
