### ISSUE TITLE
Server error will show for donor when helpseeker reserved donor's food.

### ISSUE THREAD

**Issue by Chuanqi927** [gcivil-nyu-org/urban-thrifter#173]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

Server error will show for donor when helpseeker reserved donor's food.

## Expected Behavior

Donor should see the change of resources in their donation section.

## Current Behavior

It shows server error.

## Ideas for Improvement

No idea why this happened.

## Steps to Reproduce

1. Log in as donor.

2. Make a new donation.

3. Log in as helpseeker in another browser tab.

4. Reserve that donation.

5. Go back to donor page and refresh donation section.

## Context (Environment)

It seems that we can not log in as two accounts in the same browser. This might affect when we are testing this application.

**Comment by jgingh7** [comment]
Thanks for your time debugging our website! This is an error since no two accounts are able to be used for Chrome (I assume this is your browser). Try using incognito mode for an account.
