### ISSUE TITLE
Server Error when help seeker try reserving a donation without selecting a drop off time

### ISSUE THREAD

**Issue by DarkBruce** [gcivil-nyu-org/urban-thrifter#175]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When a help seeker try to reserve for a specific donation, if the help seeker didn't select a Drop-off Time and click the reserve button, the system would reply with a Server Error (500). It's not necessarily a bug but it would be better to inform the user to select a valid drop off time before clicking the reserve button.

## Expected Behavior

A warning message that informs user to select a drop off time.

## Current Behavior

Server Error (500) is showed and takes the user back to the home page

## Ideas for Improvement

Implement a check for the help seeker's submission, if the user didn't select a drop off time, display a warning message to inform user to select one.

## Steps to Reproduce

1. Login as help seeker;

2. Click the "Checkout Resource Map";

3. Click the "Reservation" button;

4. Choose one donation to reserve without selecting a drop off time.

## Context (Environment)

If I did select a drop off time, the system works perfectly. But idealy, there should be a message that reminds users selecting a drop off time in case that the user forgets to do so.

**Comment by gcivil-nyu** [comment]
+1 I had the same issue.

**Comment by jgingh7** [comment]
Thanks for taking the time debugging our website. Closing since duplicate.
