### ISSUE TITLE
Could not find indication whether Get In Touch form works or not

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/urban-thrifter#179]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

After Submitting a test feedback, the page refreshes and does not show if it was successful or not.

## Expected Behavior

There could be some transient pop ups or email to reveal if feedback is successfully sent.

## Current Behavior

The page refreshes and appears like nothing has happened.

## Ideas for Improvement

Add some transient pop ups or email to reveal if feedback is successfully sent.
Or if time constraints, simply leave an email address on the page.

## Steps to Reproduce

1. Send a feedback in the homepage Get In Touch section.
2. the page refreshes and the user could not know if their feedback is sent or not.

## Context (Environment)

na.

**Comment by leelightman** [comment]
Thanks for the suggestion! As of now we do not have the get in touch form implemented yet as mentioned in the User Guide :)
