### ISSUE TITLE
As a help seeker, I want to receive notifications of availability of the desired resources so that I can reserve those resources.

### ISSUE THREAD

**Issue by rahulgarg97** [gcivil-nyu-org/urban-thrifter#18]
**User story**
A help seeker will be notified when a new offer is added to a category added on their watchlist within their borough.

**Acceptance criteria**
- [x] Help seeker receives the notification of the correct category resources that they had in their watchlist added in the borough they put in when they register
- [ ] Once the help seeker clicks on the notification, the map will be re-center to the new post

**Definition of Done**
- Acceptance criteria met
- code tested and reviewed / tested
- code pushed to the development branch

**Comment by leelightman** [comment]
https://github.com/django-notifications/django-notifications
https://pypi.org/project/django-notification/0.1.5/
