### ISSUE TITLE
Redirect to My Page after logging in.

### ISSUE THREAD

**Issue by jackxujh** [gcivil-nyu-org/urban-thrifter#183]
Instead of directing the user with the help seeker role to the home page, I expect to see the map or things that matter to me after logging in.

**Comment by jgingh7** [comment]
Thanks for taking the time to debug our website! Closing due to duplicate.

**Comment by jackxujh** [comment]
@jgingh7 got it. if possible, please mention or add the original issue in the comment when closing.
