### ISSUE TITLE
Not able to log in using hs_test1

### ISSUE THREAD

**Issue by gururaj3** [gcivil-nyu-org/urban-thrifter#186]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

I tried to login using hs_test1 and UT_test123! but I was not able to log in

## Expected Behavior

I should be able to login as a Helpseeker 

## Current Behavior

Denied access for login

## Steps to Reproduce

https://urban-thrifter.herokuapp.com/login/

1. 

2. 

3. 

4.

**Comment by leelightman** [comment]
The test account was deleted. I have recreated the hs_test1 account
