### ISSUE TITLE
Reservation does not show in the list of reservations

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/urban-thrifter#187]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

I logged on as a help seeker, resreved a food donation and was expecting to see it in the list of my reservations. However the list remained empty

## Expected Behavior

The list of reservations logically should show my reservations 

## Current Behavior

The list is empty

## Steps to Reproduce

1.  Login as help seeker, made a reservation for an apple
See 
<img width="1193" alt="Screen Shot 2020-11-25 at 6 49 35 PM" src="https://user-images.githubusercontent.com/53953892/100292704-3bf89200-2f4f-11eb-8fa5-7aebabe69804.png">

2. Click on Reservations on the left

3. Click on "Reserved" 

4. See nothing in the list
<img width="1200" alt="Screen Shot 2020-11-25 at 6 52 07 PM" src="https://user-images.githubusercontent.com/53953892/100292736-57fc3380-2f4f-11eb-938f-229eb7619a67.png">

**Comment by sesha14** [comment]
Professor, the reserved item shows up in the "pending" tab of help seeker as help seeker is currently awaiting confirmation from the donor. Once the donor confirms the reservation, the status changes to reserved and the help seeker can then see the item in the "reserved" tab.

**Comment by gcivil-nyu** [comment]
Ok, looks like WAI ( working as intended)
