### ISSUE TITLE
Didn't receive email verification link

### ISSUE THREAD

**Issue by gururaj3** [gcivil-nyu-org/urban-thrifter#188]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

I tried to create a new donor account and I dint receive an email verification link. Now I am stuck where it shows that the email is already registered but I can''t login as my email is not verified.

## Expected Behavior

I should have received an email verification link to verify my account.

## Steps to Reproduce

1. 

2. 

3. 

4.

**Comment by jgingh7** [comment]
Thanks your time on debugging our site! Closing since it is a duplicate
