### ISSUE TITLE
Enhancement: Clear distinction between logged in as a Donor or Helpseeker

### ISSUE THREAD

**Issue by gururaj3** [gcivil-nyu-org/urban-thrifter#189]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

When I logged in as both donor and helpseeker, I wasn't able to differentiate whether I was logged in as a donor or helpseeker because the landing page still displays "Join as helpseeker" and "Join as Donor" irrespective whether logged in as Donor or Helpseeker.

## Steps to Reproduce

1. 

2. 

3. 

4.

**Comment by jgingh7** [comment]
Thanks for taking the time to debug our website! Closing due to duplicate.
