### ISSUE TITLE
Notification icon changes when you reload the page

### ISSUE THREAD

**Issue by shivangpandya** [gcivil-nyu-org/urban-thrifter#191]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

## Expected Behavior

When I receive notification , I should see the number of notifications on the notification icon

## Current Behavior

The notification icon changes to an open mailbox for some reason when you reload the page and changes back again or even when you move around the pages 

## Steps to Reproduce

1. 

2. 

3. 

4.

**Comment by leelightman** [comment]
Hi! Thanks for the report :D are you logging in as donor or helpseeker? which notification exactly?

**Comment by shivangpandya** [comment]
Hi , the notification icon on the top which shows the number of notification. I think I logged in as a helpseeker. Try creating some donation and the healthseeker receives notification alert. When you try to move across tabs , not opening the notification the icon should appear for like 2-3 seconds
