### ISSUE TITLE
Enhancement: When I login in as a donor/help-seeker and when I haven't logged in the same home page appears.

### ISSUE THREAD

**Issue by Ritukuklani** [gcivil-nyu-org/urban-thrifter#192]
Issue tracker is ONLY used for reporting bugs. New features should be discussed in its own thread on the #general channel of slack.

I can see the option to register as a donor as well as a help-seeker, even when I have logged as a help-seeker, as the same home page is used. The UI experience can be enhanced by having minor changes in the home page.

## Steps to Reproduce

1. 

2. 

3. 

4.

**Comment by jgingh7** [comment]
Thank you for your time debugging our site! Closing since duplicate.
