### ISSUE TITLE
As a help seeker, I want to reserve the desired available resource so that I can get it for my use.

### ISSUE THREAD

**Issue by rahulgarg97** [gcivil-nyu-org/urban-thrifter#20]
**User story**
On the interactive map, a help seeker can click a resource or donation and select to reserve it by choosing an available time slot

**Acceptance criteria**
- [x] Help seeker is able to make the reservation for that resource
- [ ] After he/she reserves the resource, the exact drop-off location is provided
- [x] Once the help seeker reserve, the donation status changes from 'available' to 'pending' 

**Definition of Done**
- Acceptance criteria met
- Code tested and reviewed
- Code pushed to the development branch

**Comment by leelightman** [comment]
https://pypi.org/project/django-reservation/
