### ISSUE TITLE
Context Diagram missing user persona names

### ISSUE THREAD

**Issue by gcivil-nyu** [gcivil-nyu-org/urban-thrifter#6]
https://github.com/gcivil-nyu-org/urban-thirfter/wiki/High-Level-Analysis , the avatars/pictures of user personas do not have names, this makes it confusing, please add names

**Comment by leelightman** [comment]
New diagram uploaded. https://github.com/gcivil-nyu-org/urban-thirfter/wiki/High-Level-Analysis
